In [8]:
import numpy as np
import itertools

import import_ipynb
import def_sudoku

In [19]:
grille_test = np.array(
    [
        [1, 7, 9, 6, 0, 3, 5, 0, 4],
        [5, 8, 6, 4, 0, 0, 1, 9, 0],
        [0, 2, 4, 9, 0, 5, 0, 0, 0],
        [0, 0, 0, 2, 0, 0, 9, 0, 0],
        [0, 0, 0, 0, 7, 0, 0, 3, 0],
        [8, 0, 0, 3, 0, 0, 0, 0, 6],
        [0, 0, 0, 1, 3, 2, 0, 4, 0],
        [0, 0, 1, 7, 6, 0, 0, 0, 8],
        [7, 0, 0, 5, 9, 8, 0, 1, 2],
    ]
)

grille_test_medium = np.array(
    [
        [0, 7, 0, 0, 8, 0, 0, 0, 0],
        [0, 0, 6, 0, 2, 0, 1, 0, 3],
        [0, 2, 0, 9, 0, 0, 8, 0, 0],
        [4, 0, 7, 0, 5, 6, 9, 0, 0],
        [0, 0, 0, 8, 7, 0, 0, 0, 0],
        [0, 1, 0, 3, 0, 0, 2, 0, 6],
        [0, 5, 0, 1, 0, 2, 0, 0, 9],
        [2, 0, 1, 0, 6, 0, 3, 5, 0],
        [7, 4, 0, 0, 0, 8, 0, 1, 0],
    ]
)

grille_test_difficile = np.array(
    [
        [0, 4, 3, 0, 8, 0, 2, 5, 0],
        [6, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 9, 4],
        [9, 0, 0, 0, 0, 4, 0, 7, 0],
        [0, 0, 0, 6, 0, 8, 0, 0, 0],
        [0, 1, 0, 2, 0, 0, 0, 0, 3],
        [8, 2, 0, 5, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 5],
        [5, 3, 4, 8, 9, 0, 7, 1, 0],
    ]
)

In [9]:
for _ in range(100):
    def_sudoku.obvious_fill(grille_test)

In [10]:
grille_test

array([[1, 7, 9, 6, 8, 3, 5, 2, 4],
       [5, 8, 6, 4, 2, 7, 1, 9, 3],
       [3, 2, 4, 9, 1, 5, 8, 6, 7],
       [4, 3, 7, 2, 5, 6, 9, 8, 1],
       [9, 6, 2, 8, 7, 1, 4, 3, 5],
       [8, 1, 5, 3, 4, 9, 2, 7, 6],
       [6, 5, 8, 1, 3, 2, 7, 4, 9],
       [2, 9, 1, 7, 6, 4, 3, 5, 8],
       [7, 4, 3, 5, 9, 8, 6, 1, 2]])

In [20]:
for _ in range(100):
    def_sudoku.obvious_fill(grille_test_medium)

In [21]:
grille_test_medium

array([[0, 7, 0, 0, 8, 0, 0, 0, 0],
       [0, 0, 6, 0, 2, 0, 1, 0, 3],
       [0, 2, 0, 9, 0, 0, 8, 0, 0],
       [4, 0, 7, 2, 5, 6, 9, 0, 0],
       [0, 0, 0, 8, 7, 0, 0, 0, 0],
       [0, 1, 0, 3, 0, 0, 2, 0, 6],
       [0, 5, 0, 1, 0, 2, 0, 0, 9],
       [2, 0, 1, 0, 6, 0, 3, 5, 0],
       [7, 4, 0, 5, 0, 8, 6, 1, 2]])

In [12]:
for _ in range(100):
    def_sudoku.obvious_fill(grille_test_difficile)

In [13]:
grille_test_difficile

array([[0, 4, 3, 0, 8, 0, 2, 5, 0],
       [6, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 9, 4],
       [9, 0, 0, 0, 0, 4, 0, 7, 0],
       [0, 0, 0, 6, 0, 8, 0, 0, 0],
       [0, 1, 0, 2, 0, 0, 0, 0, 3],
       [8, 2, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 5],
       [5, 3, 4, 8, 9, 0, 7, 1, 0]])